### ISSUE TITLE
Enabling including package.json

### ISSUE THREAD

**Issue by sir-captainmorgan21** [pmachaux/ng-cli-tsc-builder#1]
Not sure if you are still supporting this package, but an option of `publishable` would be nice. This option would cause the builder to also copy over the package.json to the dist.

**Comment by sir-captainmorgan21** [comment]
Im open to creating a PR. Just let me know

**Comment by pmachaux** [comment]
Hi,
I am not maintaining it, but if you make a PR, I will review it and merge it.
If you prefer you can also fork the project of course.

**Comment by sir-captainmorgan21** [comment]
@pmachaux ok awesome. Will knock that out now. This is nice for mono repos that have publishable packages. Up until NG13, you could build you commonjs package using angular's package builder. But with NG13, Angular stopped supporting commonjs. We are using webdriverio for e2e testing and right now webdriverio does not support ESM. :(

**Comment by sir-captainmorgan21** [comment]
@pmachaux do you mind giving me permission to contribute?

**Comment by sir-captainmorgan21** [comment]
Actually Ill just fork and PR

**Comment by sir-captainmorgan21** [comment]
OK @pmachaux opened PR

**Comment by pmachaux** [comment]
@sir-captainmorgan21 , saw you forked the project and merged your PR there. Do you want me to include those changes in this project too?
